import Patient from "../models/patient";

export const FakeData = [
    // {
    //     "key": '1',
    //     "name": 'John Brown',
    //     "code": 'A123IFNFV',
    //     "age": 32,
    //     "gender": 'male',
    //     "phone": '695451282',
    //     "address": 'New York No. 1 Lake Park',
    //     "appointmentDate": '',
    //     "dateOfRecordEntry": '',
    //     "status": 'pending'
    // },
    {
        key: '2',
        name: 'Jim Green',
        code: 'A123IVFFV',
        age: 42,
        gender: 'female',
        address: 'London No. 1 Lake Park',
        phone: '695451285',
        appointmentDate: '',
        dateOfRecordEntry: '',
        status: 'missed',
    },
    {
        key: '3',
        name: 'Joe Black',
        code: 'A123IFNCT',
        age: 32,
        gender: 'male',
        phone: '695451284',
        address: 'Sidney No. 1 Lake Park',
        appointmentDate: '',
        dateOfRecordEntry: '',
        status: 'rescheduled',
    },
    {
        key: '4',
        name: 'John Brown',
        code: 'A123IFNFV',
        age: 32,
        gender: 'male',
        phone: '695451282',
        address: 'New York No. 1 Lake Park',
        appointmentDate: '',
        dateOfRecordEntry: '',
        status: 'passed'
    },
    {
        key: '5',
        name: 'Jim Green',
        code: 'A123IVFFV',
        age: 42,
        gender: 'female',
        address: 'London No. 1 Lake Park',
        phone: '695451285',
        appointmentDate: '',
        dateOfRecordEntry: '',
        status: 'missed',
    },
    {
        key: '6',
        name: 'Joe Black',
        code: 'A123IFNCT',
        age: 32,
        gender: 'male',
        phone: '695451284',
        address: 'Sidney No. 1 Lake Park',
        appointmentDate: '',
        dateOfRecordEntry: '',
        status: 'rescheduled',
    },
    {
        key: '7',
        name: 'John Brown',
        code: 'A123IFNFV',
        age: 32,
        gender: 'male',
        phone: '695451282',
        address: 'New York No. 1 Lake Park',
        appointmentDate: '',
        dateOfRecordEntry: '',
        status: 'passed'
    },
    {
        key: '8',
        name: 'Jim Green',
        code: 'A123IVFFV',
        age: 42,
        gender: 'female',
        address: 'London No. 1 Lake Park',
        phone: '695451285',
        appointmentDate: '',
        dateOfRecordEntry: '',
        status: 'missed',
    },
    {
        key: '9',
        name: 'Joe Black',
        code: 'A123IFNCT',
        age: 32,
        gender: 'male',
        phone: '695451284',
        address: 'Sidney No. 1 Lake Park',
        appointmentDate: '',
        dateOfRecordEntry: '',
        status: 'rescheduled',
    },
    {
        key: '10',
        name: 'Joe Black',
        code: 'A123IFNCT',
        age: 32,
        gender: 'male',
        phone: '695451284',
        address: 'Sidney No. 1 Lake Park',
        appointmentDate: '',
        dateOfRecordEntry: '',
        status: 'rescheduled',
    },
];
// export  const FakeData=[
//     JSON.stringify(new Patient('1','Joe Black','male',32,'A123IFNCT','695451284','Sidney No. 1 Lake Park','Douala','','','','rescheduled','','note before','note after')),
//     JSON.stringify(new Patient('2', 'Jim Green', 'female', 42, 'A123IVFFV', '695451285', 'London No. 1 Lake Park', 'Douala', '', '', '', 'missed', '', 'before','')),
//     JSON.stringify(new Patient('3', 'John Brown', 'male', 32, 'A123IFNFV', '695451282', 'New York No. 1 Lake Park', 'Douala','','','', 'passed','','before','after')),
//     JSON.stringify(new Patient('4','Joe Black','male',32,'A123IFNCT','695451284','Sidney No. 1 Lake Park','Douala','','','',''rescheduled'','','note before','note after')),
//     JSON.stringify(new Patient('5', 'Jim Green', 'female', 42, 'A123IVFFV', '695451285', 'London No. 1 Lake Park', 'Douala', '', '', '', 'missed', '', 'before','')),
//     JSON.stringify(new Patient('6', 'John Brown', 'male', 32, 'A123IFNFV', '695451282', 'New York No. 1 Lake Park', 'Douala','','','', 'passed','','before','after')),
//     JSON.stringify(new Patient('7','Joe Black','male',32,'A123IFNCT','695451284','Sidney No. 1 Lake Park','Douala','','','',''rescheduled'','','note before','note after')),
//     JSON.stringify(new Patient('8', 'Jim Green', 'female', 42, 'A123IVFFV', '695451285', 'London No. 1 Lake Park', 'Douala', '', '', '', 'missed', '', 'before','')),
//     JSON.stringify(new Patient('9', 'John Brown', 'male', 32, 'A123IFNFV', '695451282', 'New York No. 1 Lake Park', 'Douala','','','', 'passed','','before','after'))
// ]
